/**
 * Welcome to Cloudflare Workers! This is your first workers
 *
 * - Run `npm run dev` in your terminal to start a development server
 * - Open a browser tab at http://localhost:8787/ to see your worker in action
 * - Run `npm run deploy` to publish your worker
 *
 * Bind resources to your worker in `wrangler.toml`. After adding bindings, a type definition for the
 * `Env` object can be regenerated with `npm run cf-typegen`.
 *
 * Learn more at https://developers.cloudflare.com/workers/
 */

export default {
	async fetch(request, env, ctx): Promise<Response> {
console.log(request.headers);
console.log(request.body);
const html=`<!DOCTYPE html>
		<body>
		  <h1>Hello World</h1>
		  <p>This Markup was generated by a Cloudflare s orker.</p>
		</body>`;

const remote="https://github.com/venkatesh2100";
// const destination="https://github.com/venkatesh2100";
const codestatus=301;
// return Response.redirect(destination,statuscode);
// return new Response(html,{
// headers: {
//         "content-type": "text/html;charset=UTF-8",
//       },
// })
if(request.method==="GET"){
	return Response.json({
		"code":"Hi ra KODI mukkala Mahesh"
	})
}else{
	return Response.json({
		"message":"You didn't got the GET Request KONA"
	}  )
}
 return await fetch(remote,request);

		// return  Response.json({
		// 	mess dage:"Hello Bhai"

		// });
	},

} satisfies ExportedHandler<Env>;